### PR TITLE
My changes

### PR DESCRIPTION
**Pull request by GuidoDechamps**
Implemented two simple scenarios, added unit tests "framework". Moved slow integration test separately.

### CODE REVIEW

**Comment by michelgrootjans** [comment]
Thank you so much. Could you also add an alternative that reads from a json file instead of a json REST service?

We intend to use a REST service during our session. However, if the network gods feel they didn't get enough human sacrifices, we could switch to local files.

**Comment by GuidoDechamps** [comment]
Ok, will do. I only have the big MB size json file. Could you give a short inventory of the type of events and their meaning? Because i was guessing :-)

**Comment by tcoopman** [comment]
@GuidoDechamps thanks! You can find all the events that are available here: https://github.com/tcoopman/playing_with_projections_server/blob/master/lib/quizzy/events.ex

If the meaning is not clear of one of them, let us know and we will document them.
All the data files are in the data folder.

**Comment by GuidoDechamps** [comment]
Do you want the client to be able to run standalone? Have the data files locally in the repo? Or will you provide the participants with the json files when there are network problems?

**Comment by tcoopman** [comment]
The files will be local in the repo in case of network problems

**Comment by michelgrootjans** [comment]
The data files are available under `/data`. From the java dir that is `../data` ;-)

Also, I have absolutely no idea what command to run to see the projection output. When I start `./gradlew bootRun`, it prints nothing

**Comment by michelgrootjans** [comment]
Do you have some time to finish this 'relatively' soon?

**Comment by GuidoDechamps** [comment]
Define soon :-) And how do you want to see the output? It is printed now just along with all the other logs. In the inital version everything was printed as  a demo so you cloud clearly see it.

**Comment by tcoopman** [comment]
@GuidoDechamps tonight?

the output printed is just fine :+1:

**Comment by GuidoDechamps** [comment]
Hmm i try but i already have some other obligations. But i'll see if i can squeeze in some hours after ten.

**Comment by tcoopman** [comment]
@GuidoDechamps for the moment I merged the request of @krishofmans because I got that working first and we want a working implementation for tomorrow.

I don't know enough about the java ecosystem to evaluate both of your versions, but if you have any problems with the implementation of kris, then you can submit a new PR.

I'm closing this one, so no pressure for the extra hours!

Thanks a lot for the help!

**Comment by GuidoDechamps** [comment]
No problem. I 'm going to merge it now.

**Pull request closed without merging**
