### PR TITLE
adding clojure playground

### PR DESCRIPTION
**Pull request by ygrenzinger**
Following the ncraft workshop !

### CODE REVIEW

**Comment by tcoopman** [comment]
@JanVanRyswyck care to take a look at this?

@ygrenzinger can you add how this should be run to the readme?

**Comment by ygrenzinger** [comment]
I have added a clojure/README.md.
I will add some info.

**Comment by ygrenzinger** [comment]
I have "refactored" the clojure/README.md

**Comment by tcoopman** [comment]
Thanks, going to try this later today and merge it then.

**Comment by ygrenzinger** [comment]
No news ? :(

**Comment by tcoopman** [comment]
Thanks and sorry for the wait

**Pull request merged**
